### ISSUE TITLE
Include only required vendor details while fetching details from API

### ISSUE THREAD

**Issue by raghav-rumsan** [rahataid/rahat-platform#25]
GET
[/api/v1/vendors]  (/api/docs#/vendors/VendorsController_findAll)

The list api should only return `{ name, isApproved, walletAddress, isActive ,_count}`

**Comment by devkishor8007** [comment]
Would you please assign this to me?

**Comment by devkishor8007** [comment]
I got an issue while setup the repo

when I did `$ yarn start` 
### the issue:
```
Error: Cannot find module 'passport'
```

then I am installing passport 
`$ yarn add passport`

again start the repo `$ yarn start`
### again got an issue:
```
rahat-backend/node_modules/inquirer/lib/utils/screen-manager.js:4
const wrapAnsi = require('wrap-ansi');
```

Would you please help me to setup the repo?

Thank you.

**Comment by raghav-rumsan** [comment]
Due to cache issues with yarn, it's better to use npm, delete node_modules and run npm i it should solve the issue.

**Comment by devkishor8007** [comment]
@raghav-rumsan this issue is already done it!
