### ISSUE TITLE
Fix the API for users and all the missing apis,

### ISSUE THREAD

**Issue by manjik-rumsan** [rahataid/rahat-platform#69]

**Comment by karun-rumsan** [comment]
users  pagination  -> need to be page and perPage as parmaeter but there is an  order and sort in api
same as in roles 
roles assign not implemented in  roles and permission api
get user by uuid: there is no roles defined of the users
/api/v1/users/{uuid}/roles:    uuid is not accepting as the parameter
  "name": "Manager",
  "isSystem": false,
  "permissions": {   //  only "user" is acceptable not other is this pattern necessary to be implemetend while creating the permission //
    "user": [
      "manage",  
      "read"
    ]
  }
}

**Comment by bipinparajuli** [comment]
@karun-rumsan  {
  ALL: 'all',
  PUBLIC: 'public',
  USER: 'user',
  ROLE: 'role',
} these are the subject where permission can be assigned on role create API

**Comment by bipinparajuli** [comment]
[/v1/users/{uuid}/roles](http://localhost:5500/swagger#/Users/UsersController_getRoles) for getting roles by userid
